package com.example.android.helloworld

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle

// MainActivity class extends AppCompatActivity
class MainActivity : AppCompatActivity() {
    // Override onCreate method in AppCompatActivity()
    override fun onCreate(savedInstanceState: Bundle?) {
        // Call super.onCreate method
        super.onCreate(savedInstanceState)
        // Import from res/layout/activity_main.xml
        // R.layout.activity_main is generated by the Android build system
        setContentView(R.layout.activity_main)
    }
}